### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by arnaduk** [bagarrattaa/email-nuker#22]

**Comment by bagarrattaa** [comment]
@arnaduk  I intentionally turned it off temporarily due to many gmail ids getting banned+need more gmail ids+ less people are donating gmail ids. I will turn it on whenever i get some more gmail ids. You can donate me gmail ids+password in my discord dms. And also, if you are donating then, don't add phone verification while or after making gmail account and, don't sign out from all devices and keep all devices signed out for more than 20 hours and if you do so, gmail id may get bugged
